# Neden numpy?

In [2]:
import numpy as np 

In [3]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a*b

array([ 5, 12, 21, 32])

In [4]:
a = np.array([1,2,3,4])
type(a)

numpy.ndarray

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,5), dtype=int )

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.full((3,5),35 )

array([[35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35]])

In [8]:
np.full((3,5),35,dtype =int )

array([[35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35]])

In [9]:
np.linspace(0,5,5,dtype =int)

array([0, 1, 2, 3, 5])

In [10]:
np.random.normal(10,4,(3,4)) # normal (Gaussian) distribution.
#s = np.random.normal(mu, sigma, 1000)

array([[12.63049204, 11.3873431 , 11.59691424, 11.64678522],
       [17.0118527 ,  6.72411639,  5.36415131, 12.06068621],
       [11.65059317,  8.85476471,  8.97384898, -0.02252905]])

# ÖZELLİKLER:
* ndim :boyut sayısı 
* shape: boyut bilgisi
* size : toplam eleman sayısı 
* dtype : array veri tipi 

In [11]:
import numpy as np 

In [12]:
a = np.random.randint(10, size =10)
a

array([4, 8, 8, 8, 4, 9, 5, 1, 6, 5])

In [13]:
a.ndim

1

In [14]:
a.shape

(10,)

In [15]:
a.size

10

In [16]:
a.dtype

dtype('int32')

In [17]:
b = np.random.randint(10, size =(3,5))
b

array([[4, 0, 4, 2, 9],
       [8, 7, 0, 0, 1],
       [8, 6, 6, 5, 8]])

In [18]:
b.ndim

2

In [19]:
b.shape

(3, 5)

In [20]:
b.size

15

In [21]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (reshape)

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a= np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b=a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
b.ndim

2

# Array Birleştirme

In [27]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [28]:
np.concatenate([x,y]) #numpy array leri birlestirir

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
z = np.array([9,10,11,12])

In [30]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Array Ayırma

In [31]:
x =np.array([1,2,3,99,99,3,2,1])

In [32]:
a,b,c= np.split(x, [3,5]) #3'e kadar ve 5'e kadar 

In [33]:
a


array([1, 2, 3])

In [34]:
b

array([99, 99])

In [35]:
c

array([3, 2, 1])

In [36]:
m =np.arange(16).reshape(4,4) #2 boyutlu array olusturuldu
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
ust,alt= np.vsplit(m,[2]) #vertical
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
sag,sol =np.hsplit(m,[2]) #horizantal

In [40]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [41]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [42]:
x =np.array([1,2,5,7,3])
x

array([1, 2, 5, 7, 3])

In [43]:
np.sort(x)

array([1, 2, 3, 5, 7])

In [44]:
x

array([1, 2, 5, 7, 3])

In [45]:
x.sort()
x

array([1, 2, 3, 5, 7])

#numpy'ın içinden cagirildiginda veri setinin
#orijinal yapısını bozmadı 
#OOP tarzı ile cagirildiginda nesneyi kalıcı olarak degistirdi

#iki boyutlu array sıralama :

In [46]:
m =np.random.normal(20, 5, (3,3))
m

array([[16.680006  , 15.37470284, 20.17638303],
       [18.64763592, 19.10808348, 16.46636041],
       [ 7.61158209, 18.32319092, 25.56570017]])

In [47]:
np.sort(m, axis = 1) #yatay olarak sıralıyor 

array([[15.37470284, 16.680006  , 20.17638303],
       [16.46636041, 18.64763592, 19.10808348],
       [ 7.61158209, 18.32319092, 25.56570017]])

In [48]:
np.sort(m, axis = 0) #dikey olarak sıralıyor 

array([[ 7.61158209, 15.37470284, 16.46636041],
       [16.680006  , 18.32319092, 20.17638303],
       [18.64763592, 19.10808348, 25.56570017]])

# Index ile Elemanlara Erismek

In [49]:
a = np.random.randint(10, size =10)
a

array([4, 2, 9, 0, 9, 2, 6, 7, 2, 4])

In [50]:
a[3]

0

In [51]:
a[-1] #tersten 1

4

In [52]:
a[0]=100
a

array([100,   2,   9,   0,   9,   2,   6,   7,   2,   4])

In [53]:
m = np.random.randint(10, size =(3,3))
m

array([[4, 5, 7],
       [2, 6, 7],
       [9, 5, 6]])

In [54]:
m[0,2]

7

In [55]:
m[1,1]

6

In [56]:
m[1,1]= 2.2
m

array([[4, 5, 7],
       [2, 2, 7],
       [9, 5, 6]])

#2.2 degerini eklemis fakat int'e cevirerek
#arrayi olustururken bir tane bile float olsa 
array turu float olur 


# Array Alt Küme İşlemleri

In [57]:
a= np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [58]:
a[0:3] #0'dan 3'e kadar 

array([10, 11, 12])

In [59]:
a[1::3] #1,4,7.index

array([11, 14, 17])

In [60]:
m= np.random.randint(10, size=(5,5))
m

array([[8, 6, 8, 4, 9],
       [0, 2, 2, 4, 5],
       [8, 3, 2, 8, 0],
       [8, 9, 9, 8, 1],
       [9, 0, 2, 3, 0]])

In [61]:
m[:,0] #1.sutun

array([8, 0, 8, 8, 9])

In [62]:
m[:,1] #2.sutun

array([6, 2, 3, 9, 0])

In [63]:
m[0,:] #0.satır ve tum sutunlar

array([8, 6, 8, 4, 9])

In [64]:
m[0] #0.satır ve tum sutunlar

array([8, 6, 8, 4, 9])

In [65]:
m[1,:] #1.satır ve tum sutunlar

array([0, 2, 2, 4, 5])

In [66]:
m[0:2, 0:3] #ilk kısım satır ikinci kısım sutun

array([[8, 6, 8],
       [0, 2, 2]])

In [67]:
m[:,0:2]

array([[8, 6],
       [0, 2],
       [8, 3],
       [8, 9],
       [9, 0]])

In [68]:
mm= np.random.randint(10, size=(5,5))
mm

array([[9, 0, 5, 0, 9],
       [5, 6, 0, 5, 8],
       [0, 3, 0, 2, 2],
       [8, 4, 8, 8, 8],
       [0, 0, 8, 7, 4]])

In [69]:
alt_mm= mm[0:3, 0:2]
alt_mm

array([[9, 0],
       [5, 6],
       [0, 3]])

In [70]:
alt_mm[0,0] = 999
alt_mm

array([[999,   0],
       [  5,   6],
       [  0,   3]])

In [71]:
mm

array([[999,   0,   5,   0,   9],
       [  5,   6,   0,   5,   8],
       [  0,   3,   0,   2,   2],
       [  8,   4,   8,   8,   8],
       [  0,   0,   8,   7,   4]])

#Now if we modify this subarray, we'll see that the original array is changed!
#This default behavior is actually quite useful: it means that when we work with large datasets, 
#we can access and process pieces of these datasets without the need to copy the underlying data buffer.

In [72]:
b= np.random.randint(10, size=(5,5))
b


array([[8, 4, 3, 3, 4],
       [2, 2, 3, 8, 2],
       [0, 1, 5, 6, 4],
       [5, 0, 4, 5, 6],
       [3, 5, 3, 7, 9]])

In [73]:
alt_b = b[0:3, 0:2].copy()
alt_b

array([[8, 4],
       [2, 2],
       [0, 1]])

In [74]:
alt_b[0,0] = 999
alt_b

array([[999,   4],
       [  2,   2],
       [  0,   1]])

In [75]:
b

array([[8, 4, 3, 3, 4],
       [2, 2, 3, 8, 2],
       [0, 1, 5, 6, 4],
       [5, 0, 4, 5, 6],
       [3, 5, 3, 7, 9]])

#b array i degismedi
#alt kume degisti sadece 

# Fancy Index ile Elemanlara Erişmek 

In [76]:
v = np.arange(0, 30 ,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [77]:
al_getir =[1 ,3, 5]
v[al_getir]

array([ 3,  9, 15])

In [78]:
# iki boyutta fancy 
c = np.arange(1,10).reshape((3,3))
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [80]:
satir

array([0, 1])

In [81]:
sutun

array([1, 2])

In [82]:
c[satir,sutun] 
#[0,1]. index =2
#[1,2]. index =6

array([2, 6])

# simple index ve fancy index

In [83]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
c[2, [2, 0, 1]]  #simple index ve fancy index
#2,2 ve 2,0 ve 2,1 

array([9, 7, 8])

# slice ve fancy index

In [85]:
c[0:, [1,2]]  #slice ve fancy index

array([[2, 3],
       [5, 6],
       [8, 9]])

# Kosullu Eleman Islemleri

In [86]:
v = np.array([1,2,3,4,5])

In [87]:
v>5

array([False, False, False, False, False])

In [88]:
v>2

array([False, False,  True,  True,  True])

In [89]:
v[v>2] #fancy index 

array([3, 4, 5])

In [90]:
v[v !=2] #fancy index 

array([1, 3, 4, 5])

In [91]:
v

array([1, 2, 3, 4, 5])

In [92]:
v*2

array([ 2,  4,  6,  8, 10])

In [93]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

# Matematiksel Islemler

In [94]:
v = np.array([1,2,3,4,5])

In [95]:
v*5 #islemi gerceklesırken ufunc mekanizması calısıyor

array([ 5, 10, 15, 20, 25])

In [96]:
v-1

array([0, 1, 2, 3, 4])

In [97]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [98]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [99]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [100]:
np.power(v,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [101]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [102]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [103]:
np.absolute(np.array([-3]))

array([3])

In [104]:
np.sin(30)

-0.9880316240928618

In [105]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

# İki Bilinmeyenli Denklem Çözümü

5*x0 +x1 =12
x0 +3*x1 =10


In [106]:
a=np.array([[5,1],[1,3]])
a

array([[5, 1],
       [1, 3]])

In [107]:
b =np.array([12,10])
b

array([12, 10])

In [108]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [109]:
a =np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])

In [110]:
a[3,2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
np.array([3.14, 4,6,1.2])

In [ ]:
v = np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])
v[:,2]

In [ ]:
 	

import numpy as np
np.arange(1,10)

In [ ]:
list(filter(lambda x: x < 2, [1,2,3,4,5]))

In [ ]:
def yap(x,y,z):
    try:
        print(x/y*z)
    except ZeroDivisionError:
        print("gecersiz islem")

yap(1,2,0)

In [ ]:
list(map(lambda x: x*1, [2,7,4]))

In [ ]:
from functools import reduce
reduce(lambda a,b: a/b, [8,4,2])

In [ ]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2])

a+b

In [ ]:
b

In [ ]:
from functools import reduce
a = [1,2,3,4]
reduce(lambda a,b: a*b, a)

In [ ]:
A = [1,2,3,4,5]

if type(A) == ():
    print("islem gecersiz")
else:
    print(list(map(lambda x: x/1, A)))

In [ ]:
list(map(lambda x: x.upper(), ["Ali","Veli","isik"]))

In [ ]:
A = []
for i in ["ali","veli","isik"]:
    A.append(i.replace("i","a"))
print(A)

In [ ]:
list(filter(lambda x: len(x) > 8, ["pazartesi","sali","carsamba","persembe","cuma"]))

In [ ]:
A = [[1,2],[3,4],[5,6]]
list(map(lambda x: x[0]*3, A))